name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

    workflow_dispatch:
env:
  MEANING_OF_LIFE: ${{secrets.MEANING_OF_LIFE}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm ci
          npm test
